//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASPdotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MaiContent { get; set; }
        public System.DateTime DateEnter { get; set; }
        public bool IsChecked { get; set; }
    }
}
