//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASPdotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDets = new HashSet<OrderDet>();
        }
    
        public int OrderID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Total { get; set; }
        public bool IsShipping { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string Note { get; set; }
        public string UserID { get; set; }
        public Nullable<long> Fax { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> Postcode { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDet> OrderDets { get; set; }
    }
}
